name: Build Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # SDK que suporta netstandard2.1
    
    - name: Restore dependencies
      run: dotnet restore ./src/Supabase.sln
      
    - name: Build
      run: dotnet build ./src/Supabase.sln --configuration Release --no-restore
      
    - name: Run Tests Sequentially
      run: |
        # Encontra todos os projetos de teste no diretório src
        for test_project in $(find ./src -name "*.csproj" -type f | grep -i "test"); do
          echo "Running tests for: $test_project"
          dotnet test "$test_project" --no-build --configuration Release --verbosity normal
          if [ $? -ne 0 ]; then
            echo "Tests failed for $test_project"
            exit 1
          fi
          echo "Waiting 10 seconds before next test..."
          sleep 10
        done

    - name: Check Project References
      run: |
        dotnet list src/Supabase/Supabase.csproj package
        dotnet list src/Supabase.Authentication/Supabase.Authentication.csproj package 