name: Publish NuGet Package

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/publish-nuget.yml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
      
    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Release --no-restore
      
    - name: Run Tests Sequentially
      run: |
        # Encontra todos os projetos de teste no diretório src
        for test_project in $(find ./src -name "*.csproj" -type f | grep -i "test"); do
          echo "Running tests for: $test_project"
          dotnet test "$test_project" --no-build --configuration Release --verbosity normal
          if [ $? -ne 0 ]; then
            echo "Tests failed for $test_project"
            exit 1
          fi
          echo "Waiting 10 seconds before next test..."
          sleep 10
        done
      
    - name: Generate Nuget Packages
      working-directory: ./src
      run: dotnet publish -c Release

    - name: Push Package
      run: |
        for package in $(find . -name "*.nupkg"); do
          echo "Publishing package: $package"
          dotnet nuget push "$package" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate 
        done