name: Publish NuGet Package

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
      
    - name: Pack Supabase
      run: dotnet pack src/Supabase/Supabase.csproj --configuration Release --no-build --output nupkgs
      
    - name: Pack Supabase.Authentication
      run: dotnet pack src/Supabase.Authentication/Supabase.Authentication.csproj --configuration Release --no-build --output nupkgs
      
    - name: Push to NuGet
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate 